# Generated by Django 5.1.3 on 2024-12-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkteacher',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
