# Generated by Django 5.1.3 on 2025-01-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('Classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classes')),
            ],
        ),
    ]
