# Generated by Django 5.1.3 on 2024-11-20 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeacherProfile', to='users.teacher'),
        ),
    ]
